"""empty message

Revision ID: c90c94cec24f
Revises: 
Create Date: 2017-01-23 23:57:38.198713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90c94cec24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'genre')
    # ### end Alembic commands ###
